#!/bin/bash
#
# Created By: Gabriel Gonzalez (contact me at gabeg@bu.edu)
# 
# Purpose: I created this Awesome setup script so that interested users can use my
#          configuration files for their Awesome WM.
#


## Check if current user is ROOT
if [ $UID -eq 0 ]; then
    echo "ERROR: Don't run this script as ROOT."
    exit
fi


## Make screenshots directory if not present
if [ ! -d "$HOME/.screen/" ]; then 
    echo "Creating the screenshots directory at: $HOME/.screen  ..." 
    mkdir "$HOME/.screen"
fi


## Fix paths in the configuration files
echo "Modifying the file paths in the configuration files for '$USER'..."
sed -i "s/\/home\/gabeg/\/home\/$USER/g" \
    "$HOME"/.config/awesome/rc.lua \
    "$HOME"/.config/awesome/themes/theme.lua \
    "$HOME"/.config/awesome/src/keybindings.lua \
    "$HOME"/.config/awesome/src/widgets/*lua


## Download missing dependencies
echo "Downloading the dependencies..."
sudo pacman -S sysstat
sudo pacman -S lm_sensors
sudo pacman -S acpi
sudo pacman -S moc
