#!/bin/bash
#
# Created By: Gabriel Gonzalez (contact me at gabeg@bu.edu)
# 
# Purpose: I created this Awesome setup script so that interested users can use my
#          configuration files for their Awesome WM.
#

## Make screenshots directory if not present
if [ ! -d "$HOME/.screen/" ]; then 
    echo "Creating the screenshots directory at: $HOME/.screen  ..." 
    mkdir "$HOME/.screen"
fi


## Fix paths in the configuration files
echo "Modifying the file paths in the configuration files for '$USER'..."
sed -i "s/\/home\/gabeg/\/home\/$USER/g" \
    "$HOME"/.config/awesome/rc.lua \
    "$HOME"/.config/awesome/themes/theme.lua \
    "$HOME"/.config/awesome/other/scripts/comp \
    "$HOME"/.config/awesome/src/keybindings.lua \
    "$HOME"/.config/awesome/src/widgets/*lua
