#!/bin/bash
# 
# Created By: Gabriel Gonzalez
# 
# 
# Name:
# 	
# 	  syntax
# 
# 
# Syntax: 
# 	
# 	  syntax [SCRIPT_PATH] [VALUE (1-9)]
# 
# 
# Purpose:
# 	
# 	  Prints a syntax error for a script, and then shows the proper syntax
# 	  for that script.
# 
# 
# Keywords:
# 	
# 	  SCRIPT_PATH - path to the current running script
# 	  VALUE       - number of lines to print under "syntax" in the header
# 
# 
# Functions:
# 	
# 	  N/A
# 
# 
# Dependencies:
# 
#     N/A
# 
#
# Modification History:
# 	
# 	  gabeg Sep 19 2013 <> created
#
# ************************************************************************


# ********************************************
# Calculating Number of Lines In Script Syntax
# ********************************************

case $2 in

# Default Values
       "") 
	   lines=1
	   total=$[12+$lines]
	   ;;

# User Input Values
    [1-9]|[1-9][0-9]) 
	   lines="$2"
	   total=$[12+$lines]
	   ;;

# Error With Line Length
	*) 
	   echo "ERROR: Invalid line length"
	   exit
	   ;;
esac



# *****************************************
# Defining Path To Script And Script Syntax
# *****************************************

oifs=$IFS
IFS=$'\n'

loc="$1"  # path to script 
syn=(`head -$total $loc | tail -$lines | sed -e 's/^\# //'`) # script syntax


echo "ERROR: Incorrect syntax used. See the following for correct syntax"
echo -e "${syn[*]}"

exit 0
